file_format: "1"
id: matchasplit
name: matchasplit
type: shield
url: https://github.com/kata0510/Lily58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - matchasplit_left
  - matchasplit_right
